# vi: set ft=ruby :

### from git
$from_git = <<EOF
sudo yum install -y git
sudo mkdir -p /vagrant && sudo chown vagrant.vagrant -R /vagrant
git clone --depth 1 https://github.com/kazuhisya/sheepdog /vagrant/sheepdog
EOF

## from local
$from_local = <<EOF
sudo yum install -y git
sudo chown vagrant.vagrant -R /vagrant
cd /vagrant/sheepdog
git submodule update --init ./tests/unit/unity
git submodule update --init ./tests/unit/cmock
EOF

## test
$exec_test = <<EOF
sudo chown vagrant.vagrant -R /vagrant
cd /vagrant/sheepdog
sudo sh -c "echo 6144000 > /proc/sys/fs/nr_open"

# prepare
./tests/script/prepare_for_test

# exec test
#./tests/script/exec_unit
#./tests/script/exec_operation
#./tests/script/exec_functional
EOF


### main
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  # libvirt settings
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 4096
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # for local repo
  config.vm.synced_folder "./sheepdog", "/vagrant/sheepdog", disabled: "false", type: "rsync"
  config.vm.provision "shell", privileged: false, inline: $from_local
  config.vm.provision "shell", privileged: false, inline: $exec_test

  # for git repo
  #config.vm.provision "shell", privileged: false, inline: $from_git
  #config.vm.provision "shell", privileged: false, inline: $exec_test
end
