version: '2'
services:

  zoo1:
    image: docker.io/zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888
      TZ: 'JST-9'

  sheep:
    build: .
    ports:
      - 7000
    links:
      - zoo1:ZK1
    command: '/usr/sbin/sheep --cluster zookeeper:zoo1:2181 --log dst=syslog --upgrade /store -p 7000 -f'
    environment:
      TZ: 'JST-9'
    depends_on:
      - zoo1
