version: '2'
services:

  zoo1:
    image: docker.io/zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      TZ: 'JST-9'
  zoo2:
    image: docker.io/zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      TZ: 'JST-9'
  zoo3:
    image: docker.io/zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      TZ: 'JST-9'

  sheep:
    build: .
    restart: always
    ports:
      - 7000
    links:
      - zoo1:ZK1
      - zoo2:ZK2
      - zoo3:ZK3
    command: '/root/run.sh'
    environment:
      TZ: 'JST-9'
      ZOO_SERVERS: 'zoo1:2181,zoo2:2181,zoo3:2181'
    depends_on:
      - zoo1
      - zoo2
      - zoo3
